// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: example.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=name_request,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldRequest) Reset() {
	*x = WorldRequest{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldRequest) ProtoMessage() {}

func (x *WorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldRequest.ProtoReflect.Descriptor instead.
func (*WorldRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *WorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=name_response,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldResponse) Reset() {
	*x = WorldResponse{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldResponse) ProtoMessage() {}

func (x *WorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldResponse.ProtoReflect.Descriptor instead.
func (*WorldResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *WorldResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\n" +
	"kaffein.pb\x1a\x19google/api/validate.proto\"6\n" +
	"\fWorldRequest\x12&\n" +
	"\x04Name\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\fname_request\"5\n" +
	"\rWorldResponse\x12$\n" +
	"\x04Name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\rname_response2\xc1\x02\n" +
	"\n" +
	"HelloWorld\x12D\n" +
	"\rSayHelloUnary\x12\x18.kaffein.pb.WorldRequest\x1a\x19.kaffein.pb.WorldResponse\x12L\n" +
	"\x14sayHelloStreamServer\x12\x18.kaffein.pb.WorldRequest\x1a\x18.kaffein.pb.WorldRequest0\x01\x12M\n" +
	"\x14SayHelloStreamClient\x12\x18.kaffein.pb.WorldRequest\x1a\x19.kaffein.pb.WorldResponse(\x01\x12P\n" +
	"\x15sayHelloBidirectional\x12\x18.kaffein.pb.WorldRequest\x1a\x19.kaffein.pb.WorldResponse(\x010\x01B\x1fZ\x1dgithub.com/goffyshop/proto;pbb\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_goTypes = []any{
	(*WorldRequest)(nil),  // 0: kaffein.pb.WorldRequest
	(*WorldResponse)(nil), // 1: kaffein.pb.WorldResponse
}
var file_example_proto_depIdxs = []int32{
	0, // 0: kaffein.pb.HelloWorld.SayHelloUnary:input_type -> kaffein.pb.WorldRequest
	0, // 1: kaffein.pb.HelloWorld.sayHelloStreamServer:input_type -> kaffein.pb.WorldRequest
	0, // 2: kaffein.pb.HelloWorld.SayHelloStreamClient:input_type -> kaffein.pb.WorldRequest
	0, // 3: kaffein.pb.HelloWorld.sayHelloBidirectional:input_type -> kaffein.pb.WorldRequest
	1, // 4: kaffein.pb.HelloWorld.SayHelloUnary:output_type -> kaffein.pb.WorldResponse
	0, // 5: kaffein.pb.HelloWorld.sayHelloStreamServer:output_type -> kaffein.pb.WorldRequest
	1, // 6: kaffein.pb.HelloWorld.SayHelloStreamClient:output_type -> kaffein.pb.WorldResponse
	1, // 7: kaffein.pb.HelloWorld.sayHelloBidirectional:output_type -> kaffein.pb.WorldResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
