// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: example.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelloWorld_SayHelloUnary_FullMethodName         = "/kaffein.pb.HelloWorld/SayHelloUnary"
	HelloWorld_SayHelloStreamServer_FullMethodName  = "/kaffein.pb.HelloWorld/sayHelloStreamServer"
	HelloWorld_SayHelloStreamClient_FullMethodName  = "/kaffein.pb.HelloWorld/SayHelloStreamClient"
	HelloWorld_SayHelloBidirectional_FullMethodName = "/kaffein.pb.HelloWorld/sayHelloBidirectional"
)

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloWorldClient interface {
	// unary
	SayHelloUnary(ctx context.Context, in *WorldRequest, opts ...grpc.CallOption) (*WorldResponse, error)
	// stream (server)
	SayHelloStreamServer(ctx context.Context, in *WorldRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldRequest], error)
	// stream (client)
	SayHelloStreamClient(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorldRequest, WorldResponse], error)
	// bi-directional (stream)
	SayHelloBidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorldRequest, WorldResponse], error)
}

type helloWorldClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloWorldClient(cc grpc.ClientConnInterface) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) SayHelloUnary(ctx context.Context, in *WorldRequest, opts ...grpc.CallOption) (*WorldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorldResponse)
	err := c.cc.Invoke(ctx, HelloWorld_SayHelloUnary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloWorldClient) SayHelloStreamServer(ctx context.Context, in *WorldRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HelloWorld_ServiceDesc.Streams[0], HelloWorld_SayHelloStreamServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorldRequest, WorldRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HelloWorld_SayHelloStreamServerClient = grpc.ServerStreamingClient[WorldRequest]

func (c *helloWorldClient) SayHelloStreamClient(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorldRequest, WorldResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HelloWorld_ServiceDesc.Streams[1], HelloWorld_SayHelloStreamClient_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorldRequest, WorldResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HelloWorld_SayHelloStreamClientClient = grpc.ClientStreamingClient[WorldRequest, WorldResponse]

func (c *helloWorldClient) SayHelloBidirectional(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorldRequest, WorldResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HelloWorld_ServiceDesc.Streams[2], HelloWorld_SayHelloBidirectional_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorldRequest, WorldResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HelloWorld_SayHelloBidirectionalClient = grpc.BidiStreamingClient[WorldRequest, WorldResponse]

// HelloWorldServer is the server API for HelloWorld service.
// All implementations must embed UnimplementedHelloWorldServer
// for forward compatibility.
type HelloWorldServer interface {
	// unary
	SayHelloUnary(context.Context, *WorldRequest) (*WorldResponse, error)
	// stream (server)
	SayHelloStreamServer(*WorldRequest, grpc.ServerStreamingServer[WorldRequest]) error
	// stream (client)
	SayHelloStreamClient(grpc.ClientStreamingServer[WorldRequest, WorldResponse]) error
	// bi-directional (stream)
	SayHelloBidirectional(grpc.BidiStreamingServer[WorldRequest, WorldResponse]) error
	mustEmbedUnimplementedHelloWorldServer()
}

// UnimplementedHelloWorldServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloWorldServer struct{}

func (UnimplementedHelloWorldServer) SayHelloUnary(context.Context, *WorldRequest) (*WorldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloUnary not implemented")
}
func (UnimplementedHelloWorldServer) SayHelloStreamServer(*WorldRequest, grpc.ServerStreamingServer[WorldRequest]) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStreamServer not implemented")
}
func (UnimplementedHelloWorldServer) SayHelloStreamClient(grpc.ClientStreamingServer[WorldRequest, WorldResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStreamClient not implemented")
}
func (UnimplementedHelloWorldServer) SayHelloBidirectional(grpc.BidiStreamingServer[WorldRequest, WorldResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloBidirectional not implemented")
}
func (UnimplementedHelloWorldServer) mustEmbedUnimplementedHelloWorldServer() {}
func (UnimplementedHelloWorldServer) testEmbeddedByValue()                    {}

// UnsafeHelloWorldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloWorldServer will
// result in compilation errors.
type UnsafeHelloWorldServer interface {
	mustEmbedUnimplementedHelloWorldServer()
}

func RegisterHelloWorldServer(s grpc.ServiceRegistrar, srv HelloWorldServer) {
	// If the following call pancis, it indicates UnimplementedHelloWorldServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelloWorld_ServiceDesc, srv)
}

func _HelloWorld_SayHelloUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).SayHelloUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloWorld_SayHelloUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).SayHelloUnary(ctx, req.(*WorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloWorld_SayHelloStreamServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorldRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloWorldServer).SayHelloStreamServer(m, &grpc.GenericServerStream[WorldRequest, WorldRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HelloWorld_SayHelloStreamServerServer = grpc.ServerStreamingServer[WorldRequest]

func _HelloWorld_SayHelloStreamClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloWorldServer).SayHelloStreamClient(&grpc.GenericServerStream[WorldRequest, WorldResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HelloWorld_SayHelloStreamClientServer = grpc.ClientStreamingServer[WorldRequest, WorldResponse]

func _HelloWorld_SayHelloBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloWorldServer).SayHelloBidirectional(&grpc.GenericServerStream[WorldRequest, WorldResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HelloWorld_SayHelloBidirectionalServer = grpc.BidiStreamingServer[WorldRequest, WorldResponse]

// HelloWorld_ServiceDesc is the grpc.ServiceDesc for HelloWorld service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloWorld_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaffein.pb.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloUnary",
			Handler:    _HelloWorld_SayHelloUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sayHelloStreamServer",
			Handler:       _HelloWorld_SayHelloStreamServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloStreamClient",
			Handler:       _HelloWorld_SayHelloStreamClient_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "sayHelloBidirectional",
			Handler:       _HelloWorld_SayHelloBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}
